# Generated by Django 5.2.1 on 2025-06-04 00:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptops_count', models.PositiveIntegerField(default=0, verbose_name='Total de Laptops')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Inventário',
                'verbose_name_plural': 'Inventários',
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.DeleteModel(
            name='LaptopInventory',
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='laptop',
            options={'ordering': ['-created_at'], 'verbose_name': 'Laptop', 'verbose_name_plural': 'Laptops'},
        ),
        migrations.AlterUniqueTogether(
            name='laptop',
            unique_together={('brand', 'model')},
        ),
        migrations.AddField(
            model_name='brand',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)], verbose_name='Ano de Fundação'),
        ),
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_laptops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laptop',
            name='condition',
            field=models.CharField(choices=[('N', 'Novo'), ('U', 'Usado'), ('R', 'Recondicionado')], default='N', max_length=1, verbose_name='Condição'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de criação'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=10, validators=[django.core.validators.MinValueValidator(2000)]),
        ),
        migrations.AddField(
            model_name='laptop',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='laptop',
            name='specs',
            field=models.JSONField(default=dict, help_text='Especificações em formato JSON', verbose_name='Especificações Técnicas'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(help_text='Nome da marca (ex: Dell, Apple)', max_length=200, unique=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laptops', to='laptops.brand', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='model',
            field=models.CharField(help_text='Modelo específico do laptop', max_length=200, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='photo',
            field=models.ImageField(blank=True, upload_to='laptops/%Y/%m/%d/', verbose_name='Foto'),
        ),
        migrations.AddIndex(
            model_name='laptop',
            index=models.Index(fields=['brand', 'model'], name='laptops_lap_brand_i_7cbdb6_idx'),
        ),
        migrations.AddIndex(
            model_name='laptop',
            index=models.Index(fields=['price'], name='laptops_lap_price_108b15_idx'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='laptop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='laptops.laptop'),
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='factory_year',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='gpu',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='model_year',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='rom',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='value',
        ),
    ]
